backend:
  name: github
  repo: designerwebhosting/designerwebhosting.github.io # Path to your Github repository
  branch: master # Branch to update
  
media_folder: "img" # Media files will be stored in the repo under images/uploads
